const phrases = [ // ... Ajoutez autant de phrases que vous le souhaitez ...
            'Guten Morgen! Bonjour!',
            'Wie geht es dir? Comment ça va?',
            'Ich liebe dieses Wetter. J\'adore ce temps.',
            'Was ist dein Lieblingsessen? Quel est ton plat préféré?',
            'Entschuldigung, wo ist die nächste U-Bahn-Station? Excusez-moi, où est la station de métro la plus proche?',
            'Ich mag deine Schuhe. J\'aime tes chaussures.',
            'Heute ist ein besonderer Tag. Aujourd\'hui est un jour spécial.',
            'Kannst du mir bitte helfen? Peux-tu m\'aider s\'il te plaît?',
            'Ich habe mein Portemonnaie verloren. J\'ai perdu mon portefeuille.',
            'Wie spät ist es? Quelle heure est-il?',
            'Was machst du beruflich? Que fais-tu dans la vie?',
            'Das schmeckt fantastisch! C\'est délicieux!',
            'Hast du Geschwister? As-tu des frères et sœurs?',
            'Könnten Sie das bitte wiederholen? Pourriez-vous répéter s\'il vous plaît?',
            'Es tut mir leid für die Verspätung. Je m\'excuse pour le retard.',
            'Welche Musikrichtung magst du? Quel genre de musique aimes-tu?',
            'Wie ist dein Nachname? Quel est ton nom de famille?',
            'Das ist wirklich interessant. C\'est vraiment intéressant.',
            'Was machst du am Wochenende? Qu\'est-ce que tu fais le week-end?',
            'Ich habe eine Frage. J\'ai une question.',
            'Können Sie mir den Weg zeigen? Pouvez-vous me montrer le chemin?',
            'Ich habe heute viel zu tun. J\'ai beaucoup à faire aujourd\'hui.',
            'Magst du Sport? Aimes-tu le sport?',
            'Ich freue mich darauf. J\'attends ça avec impatience.',
            'Bist du müde? Es ist schon spät. Es-tu fatigué? Il est déjà tard.',
            'Kannst du bitte langsamer sprechen? Peux-tu parler plus lentement s\'il te plaît?',
            'Das war lustig! C\'était drôle!',
            'Ich wünsche dir einen schönen Tag. Je te souhaite une bonne journée.',
            'Wie ist dein Wochenende verlaufen? Comment s\'est passé ton week-end?',
            'Lass uns das nächste Mal treffen. Rencontrons-nous la prochaine fois.',
            'Ich mag deine Haare. J\'aime tes cheveux.',
            'Entschuldigen Sie die Störung. Excusez-moi de vous déranger.',
            'Welche Sprachen sprichst du? Quelles langues parles-tu?',
            'Das war lecker! C\'était délicieux!',
            'Kannst du mir bitte den Salz reichen? Peux-tu me passer le sel s\'il te plaît?',
            'Hast du einen Lieblingsfilm? Quel est ton film préféré?',
            'Ich habe das nicht verstanden. Je n\'ai pas compris.',
            'Was ist dein Lieblingsbuch? Quel est ton livre préféré?',
            'Es tut mir leid, ich habe vergessen. Désolé, j\'ai oublié.',
            'Wie ist dein Geburtstag? Quelle est ta date de naissance?',
            'Ich mag deinen Stil. J\'aime ton style.',
            'Bist du schon einmal gereist? As-tu déjà voyagé?',
            'Das ist eine gute Idee. C\'est une bonne idée.',
            'Können Sie mir bitte Wasser bringen? Pouvez-vous m\'apporter de l\'eau s\'il vous plaît?',
            'Ich habe heute viel gelacht. J\'ai beaucoup ri aujourd\'hui.',
            'Was machst du in deiner Freizeit? Qu\'est-ce que tu fais pendant ton temps libre?',
            'Ich bin nicht sicher. Je ne suis pas sûr(e).',
            'Wie ist dein Lieblingssport? Quel est ton sport préféré?',
            'Entschuldigung, ich habe mich verlaufen. Excusez-moi, je me suis perdu(e).',
            'Das ist wirklich beeindruckend. C\'est vraiment impressionnant.',
            'Hast du ein Haustier? As-tu un animal de compagnie?',
            'Kannst du gut kochen? Sais-tu bien cuisiner?',
            'Ich bin nicht sicher, was ich bestellen soll. Je ne suis pas sûr(e) de ce que je devrais commander.',
            'Das ist interessant zu wissen. C\'est intéressant de savoir.',
            'Wie ist dein Lieblingsrestaurant? Quel est ton restaurant préféré?',
            'Ich fühle mich heute gut. Je me sens bien aujourd\'hui.',
            'Was ist dein Lieblingsfach in der Schule? Quelle est ta matière préférée à l\'école?',
            'Das ist eine schwierige Frage. C\'est une question difficile.',
            'Kannst du mir bei den Hausaufgaben helfen? Peux-tu m\'aider avec mes devoirs?',
            'Ich wünsche dir viel Erfolg. Je te souhaite beaucoup de succès.',
            'Bist du kreativ? Es-tu créatif(ve)?',
            'Wie war dein Tag? Comment était ta journée?',
            'Ich bin einverstanden. Je suis d\'accord.',
            'Kannst du mir den Weg zeigen? Peux-tu me montrer le chemin?',
            'Das ist eine tolle Aussicht. C\'est une vue magnifique.',
            'Was ist dein Lieblingslied? Quelle est ta chanson préférée?',
            'Ich mag deinen Sinn für Humor. J\'aime ton sens de l\'humour.',
            'Hast du Geschwister? As-tu des frères et sœurs?',
            'Es tut mir leid für das Missverständnis. Désolé(e) pour la confusion.',
            'Welche Musikrichtung magst du? Quel genre de musique aimes-tu?',
            'Kannst du mir bitte helfen? Peux-tu m\'aider s\'il te plaît?',
            'Das ist eine interessante Frage. C\'est une question intéressante.',
            'Wie spät ist es? Quelle heure est-il?',
            'Ich bin müde. Je suis fatigué(e).',
            'Was machst du beruflich? Quel est ton métier?',
            'Ich liebe diese Stadt. J\'adore cette ville.',
            'Hast du heute schon gegessen? As-tu déjà mangé aujourd\'hui?',
            'Es war schön, dich zu treffen. C\'était agréable de te rencontrer.',
            'Was machst du gerne in deiner Freizeit? Qu\'est-ce que tu aimes faire pendant ton temps libre?',
            'Kannst du mir ein gutes Buch empfehlen? Peux-tu me recommander un bon livre?',
            'Ich bin gespannt. Je suis curieux(se).',
            'Wie geht es dir heute? Comment ça va aujourd\'hui?',
            'Ich habe eine Idee. J\'ai une idée.',
            'Kannst du mir bitte zustimmen? Peux-tu être d\'accord avec moi s\'il te plaît?',
            'Es ist ein schöner Tag. C\'est une belle journée.',
            'Was ist dein Lieblingsgetränk? Quelle est ta boisson préférée?',
            'Ich bin nicht sicher, was ich tun soll. Je ne suis pas sûr(e) de ce que je devrais faire.',
            'Hast du einen Lieblingskünstler? Quel est ton artiste préféré?',
            'Das ist wirklich beeindruckend. C\'est vraiment impressionnant.',
            'Bist du ein Frühaufsteher oder eine Nachteule? Es-tu matinal(e) ou nocturne?',
            'Ich freue mich darauf. J\'attends avec impatience.',
            'Wie verbringst du gerne deine Wochenenden? Comment aimes-tu passer tes week-ends?',
            'Das ist wirklich lustig. C\'est vraiment drôle.',
            'Hast du Haustiere? As-tu des animaux de compagnie?',
            'Ich habe das verstanden. J\'ai compris.',
            'Was ist dein Lieblingsfilm? Quel est ton film préféré?',
            'Ich freue mich auf das Wochenende. J\'attends avec impatience le week-end.',
            'Kannst du gut kochen? Sais-tu bien cuisiner?',
            'Das ist nicht fair. Ce n\'est pas juste.',
            'Hast du einen Traum, den du verwirklichen möchtest? As-tu un rêve que tu veux réaliser?',
            'Das ist interessant zu wissen. C\'est bon à savoir.',
            'Wie findest du diese Stadt? Comment trouves-tu cette ville?',
            'Ich bin stolz auf dich. Je suis fier/fière de toi.',
            'Hast du einen Lieblingsplatz? As-tu un endroit préféré?',
            'Das war ein tolles Erlebnis. C\'était une expérience formidable.',
            'Kannst du gut schwimmen? Sais-tu bien nager?',
            'Das ist eine schwierige Entscheidung. C\'est une décision difficile.',
            'Hast du eine besondere Fähigkeit? As-tu une compétence particulière?',
            'Ich habe meinen Schlüssel verloren. J\'ai perdu ma clé.',
            'Was magst du an dir selbst? Qu\'est-ce que tu aimes en toi?',
            'Das ist eine gute Frage. C\'est une bonne question.',
            'Hast du Geschichten aus deiner Kindheit? As-tu des histoires de ton enfance?',
            'Ich bin aufgeregt. Je suis excité(e).',
            'Was war dein letztes Abenteuer? Quelle a été ta dernière aventure?',
            'Hast du heute etwas Besonderes vor? As-tu quelque chose de spécial de prévu aujourd\'hui?',
            'Das ist wirklich beeindruckend. C\'est vraiment impressionnant.',
            'Kannst du mir ein Geheimnis verraten? Peux-tu me dire un secret?',
            'Wie kommst du zur Arbeit? Comment te rends-tu au travail?',
            'Ich bin dankbar. Je suis reconnaissant(e).',
            'Hast du ein Lieblingszitat? As-tu une citation préférée?',
            'Das war lustig. C\'était amusant.',
            'Was ist dein Lieblingsbuch? Quel est ton livre préféré?',
            'Das klingt interessant. Ça semble intéressant.',
            'Hast du Geschwister? As-tu des frères et sœurs?',
            'Ich habe keine Ahnung. Je n\'en ai aucune idée.',
            'Was machst du beruflich? Quel est ton métier?',
            'Ich bin mir nicht sicher. Je ne suis pas sûr(e).',
            'Hast du ein bestimmtes Ziel im Leben? As-tu un but particulier dans la vie?',
            'Das ist unglaublich. C\'est incroyable.',
            'Was ist deine Lieblingsfarbe? Quelle est ta couleur préférée?',
            'Ich bin müde. Je suis fatigué(e).',
            'Hast du eine Leidenschaft? As-tu une passion?',
            'Das ist eine gute Idee. C\'est une bonne idée.',
            'Was war dein letzter Urlaubsort? Quelle a été ta dernière destination de vacances?',
            'Ich kann nicht warten. Je ne peux pas attendre.',
            'Hast du ein Haustier? As-tu un animal de compagnie?',
            'Das ist nicht einfach. Ce n\'est pas facile.',
            'Was ist dein Lieblingssport? Quel est ton sport préféré?',
            'Ich bin beeindruckt. Je suis impressionné(e).',
            'Hast du einen besonderen Talisman? As-tu un talisman spécial?',
            'Das ist eine gute Möglichkeit. C\'est une bonne façon.',
            'Was ist deine größte Angst? Quelle est ta plus grande peur?',
            'Ich verstehe nicht. Je ne comprends pas.',
            'Hast du ein Lieblingsessen? As-tu un plat préféré?',
            'Das ist wirklich seltsam. C\'est vraiment étrange.',
            'Was sind deine Hobbys? Quels sont tes passe-temps?',
            'Ich bin neugierig. Je suis curieux(se).',
            'Hast du einen besten Freund? As-tu un meilleur ami?',
            'Das ist traurig. C\'est triste.',
            'Was ist dein Traumauto? Quelle est ta voiture de rêve?',
            'Ich mag das. J\'aime ça.',
            'Hast du schon mal etwas Verrücktes gemacht? As-tu déjà fait quelque chose de fou?',
            'Das ist fantastisch. C\'est fantastique.',
            'Wie geht es dir heute? Comment ça va aujourd\'hui?',
            'Das ist wirklich lustig. C\'est vraiment drôle.',
            'Hast du Geschmack in Musik? As-tu du goût en musique?',
            'Ich bin einverstanden. Je suis d\'accord.',
            'Was ist dein Lieblingsfilm? Quel est ton film préféré?',
            'Das ist erstaunlich. C\'est étonnant.',
            'Hast du eine Lieblingsjahreszeit? As-tu une saison préférée?',
            'Ich bin froh. Je suis content(e).',
            'Was machst du in deiner Freizeit? Qu\'est-ce que tu fais pendant ton temps libre?',
            'Das ist kompliziert. C\'est compliqué.',
            'Hast du eine besondere Fähigkeit? As-tu une compétence particulière?',
            'Ich bin mir sicher. Je suis sûr(e).',
            'Was ist dein Lieblingsgetränk? Quelle est ta boisson préférée?',
            'Das ist eine gute Frage. C\'est une bonne question.',
            'Hast du einen Lieblingsplatz? As-tu un endroit préféré?',
            'Ich bin nervös. Je suis nerveux(se).',
            'Was ist dein größter Erfolg? Quelle est ta plus grande réussite?',
            'Das ist nicht fair. Ce n\'est pas juste.',
            'Hast du einen Lieblingskünstler? As-tu un artiste préféré?',
            'Ich bin neidisch. Je suis jaloux(se).',
            'Was war das letzte Buch, das du gelesen hast? Quel a été le dernier livre que tu as lu?',
            'Das ist eine interessante Perspektive. C\'est une perspective intéressante.',
            'Hast du eine Lieblingsblume? As-tu une fleur préférée?',
            'Ich bin glücklich. Je suis heureux(se).',
            'Was ist deine beste Eigenschaft? Quelle est ta meilleure qualité?',
            'Das ist nicht meine Entscheidung. Ce n\'est pas ma décision.',
            'Hast du eine Bucket List? As-tu une liste de choses à faire avant de mourir?',
            'Ich bin stolz. Je suis fier/fière.',
            'Was ist dein Lieblingsspiel? Quel est ton jeu préféré?',
            'Das ist zu viel. C\'est trop.',
            'Hast du eine Lieblingsfernsehserie? As-tu une série télévisée préférée?',
            'Ich bin überrascht. Je suis surpris(e).',
    
  ];
  
  let currentPhraseIndex = 0;
  
  function nextPhrase() {
    const phraseElement = document.getElementById('phrase');
    phraseElement.textContent = phrases[currentPhraseIndex];
  
    currentPhraseIndex++;
    if (currentPhraseIndex === phrases.length) {
      currentPhraseIndex = 0;
    }
  }
  
  nextPhrase(); // Affiche la première phrase au chargement de la page